name: hoora
description: "A new Flutter project."
publish_to: 'none'

version: 1.4.1+13

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter: ^1.1.0
  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  flutter_secure_storage: ^9.0.0
  firebase_core: ^2.27.2
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  flutter_bloc: ^8.1.5
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  firebase_crashlytics: ^3.5.0
  firebase_analytics: ^10.10.0
  firebase_storage: ^11.7.1
  cloud_functions: ^4.7.3
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  slider_button: ^2.1.0
  http: ^1.2.1
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1-9

flutter:
  uses-material-design: true
  fonts:
    - family: BalooPaaji
      fonts:
        - asset: assets/fonts/BalooPaaji2-Bold.ttf
        - asset: assets/fonts/BalooPaaji2-ExtraBold.ttf
        - asset: assets/fonts/BalooPaaji2-Medium.ttf
        - asset: assets/fonts/BalooPaaji2-Regular.ttf
        - asset: assets/fonts/BalooPaaji2-SemiBold.ttf
    - family: ARPDisplay
      fonts:
        - asset: assets/fonts/ARPDisplay-20.ttf
        - asset: assets/fonts/ARPDisplay-40.ttf
        - asset: assets/fonts/ARPDisplay-80.ttf
        - asset: assets/fonts/ARPDisplay-150.ttf
        - asset: assets/fonts/ARPDisplay-240.ttf
  assets:
      - assets/
      - assets/animations/
      - assets/svg/
      - assets/images/

flutter_native_splash:
  ios: true
  android: false
  color: "#0C0A29"
  image: "assets/images/hoora.png"


flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  # adaptive_icon_background: "#0C0A29"
  # adaptive_icon_foreground: "assets/images/adaptive_icon_foreground.png"
