// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android {
    return const FirebaseOptions(
      apiKey: 'AIzaSyCKG6rO9BxSQBEUe2G0P8NmEhTCfb7j-xg',
      appId: '1:1041066486499:android:8c4195984c310fdd3133d6',
      messagingSenderId: '1041066486499',
      projectId: 'hoora-fb944',
      storageBucket: 'hoora-fb944.appspot.com',
    );
  }

  static FirebaseOptions get ios {
    return const FirebaseOptions(
      apiKey: 'AIzaSyAImNC-GQ9yYaOyy1qItbUgJIDbmDzAROY',
      appId: '1:1041066486499:ios:4b69bc5f4f62a93b3133d6',
      messagingSenderId: '1041066486499',
      projectId: 'hoora-fb944',
      storageBucket: 'hoora-fb944.appspot.com',
      androidClientId: '1041066486499-13v6pv5gpkcjbm711tjp0sd5r3mk0tkl.apps.googleusercontent.com',
      iosClientId: '1041066486499-f33db4fta01p2c8i36q9ohsiqtvkfsit.apps.googleusercontent.com',
      iosBundleId: 'app.hoora',
    );
  }
}